### ISSUE TITLE
Use same name in global object and node module

### ISSUE THREAD

**Issue by othree** [knowledgecode/jquery-param#1]
I am writing another JavaScript library and want to depend on jquery-param.
But a issue encounter to my project.

I am writing ES6 and use babel to translate my code to use [UMD](https://github.com/umdjs/umd) format.
The issue is babel will use only one name for both node module and global object(browser).
ex:

```
import param from 'param';
```

will translate to 

```
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    define('fetcher', ['exports', 'module', 'param'], factory);
  } else if (typeof exports !== 'undefined' && typeof module !== 'undefined') {
    factory(exports, module, require('param'));
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, mod, global.param);
    global.fetcher = mod.exports;
  }
})(this, function (exports, module, _param2) {
```

But current `jquery-param` use `jquery-param` as node module name, and use `param` as global object name for browsers. I must have one more post process to deal with this issue.

**Comment by knowledgecode** [comment]
Thanks for using this module.
Sorry, I've known Babel but have never used it. So I tried it just now for the first time :-).
How about writing as below?

``` javascript
import param from 'jquery-param';
```

**Comment by othree** [comment]
This will change the code for browser not work. From

```
    factory(mod.exports, mod, global.param);
```

to

```
    factory(mod.exports, mod, global.jqueryParam);
```

**Comment by knowledgecode** [comment]
I wrote `test.js`:

``` javascript
import param from 'jquery-param';

console.log(param('hello'));
```

and then I converted it:

``` shell
$ babel -m umd test.js
```

It seems that global.param is left. misunderstand?

``` javascript
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['exports', 'jquery-param'], factory);
  } else if (typeof exports !== 'undefined') {
    factory(exports, require('jquery-param'));
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, global.param);
    global.test = mod.exports;
  }
})(this, function (exports, _jqueryParam) {
  'use strict';

  var _interopRequire = function (obj) { return obj && obj.__esModule ? obj['default'] : obj; };

  var _param = _interopRequire(_jqueryParam);

  console.log(_param('hello'));
});
```

**Comment by othree** [comment]
Ya, you're right. I think this fix the issue. The first variable name will be global name of the lib.
