### ISSUE TITLE
files moved/removed in 1.2.0

### ISSUE THREAD

**Issue by kellyselden** [knowledgecode/jquery-param#19]
Shouldn't 1.2.0 be a breaking change instead? Since the files all moved and the .min file was removed, this causes all our builds to fail.

**Comment by knowledgecode** [comment]
Sorry, maybe I should have bumped the major version.


The .min file that was output to the root directory was restored. Check it out as it's included in the v1.2.1 npm package. If your error persists, it would be helpful if you could tell me specifically what files are missing.

**Comment by kellyselden** [comment]
Sorry I didn't get back to you. This fix should work for us. Thanks!
