### ISSUE TITLE
1.1.1 no longer has default exports for webpack

### ISSUE THREAD

**Issue by PikachuEXE** [knowledgecode/jquery-param#7]
I use webpack@4.43.0 and typescript@3.9.6
I am using the following code to import `jquery-param`
```typescript
import param from "jquery-param"
```

However as I updated to `1.1.1` I see this error message for all modules importing `jquery-param`:
`"export 'default' (imported as 'param') was not found in 'jquery-param'`

I can see the UMD code (the conditional part for `module.export`) in both versions are slightly different:
`1.0.5`:
`typeof module === 'object' && typeof module.exports === 'object'`
`1.1.1`:
`typeof exports === 'object' && typeof module !== 'undefined'`

`package.json` also now contains a `module` entry
`"module": "esm/jquery-param.es.js"`

I am not sure if the usage should be updated or this is an issue of the library

**Comment by knowledgecode** [comment]
Yikes!

Thank you for the pointing it out. It seems the consideration for webpack was insufficient. I'll fix it.

**Comment by knowledgecode** [comment]
I've fixed it and published as v1.1.2. Maybe the error should go away.

**Comment by PikachuEXE** [comment]
Yes I confirm the issue is fixed in `1.1.2`
Thanks for the quick release
